### ISSUE TITLE
Numeric properties removed from crate on load

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#106]
In version 0.78.4, it appears that crate properties with numeric values are removed upon loading.

The problematic line seems to be this:

https://github.com/describo/crate-builder-component/blob/3f35803c7135fb405cbb4320c4ebed2388626d52/src/crate-builder/CrateManager/lib.ts#L107

Here, !isEmpty(entry) is always false if the entry is a numeric value.

Here's a small test in the Lodash playground:

https://playcode.io/1984273

**Comment by marcolarosa** [comment]
Can you please put in small sample crate that I can write into the tests.

**Comment by beepsoft** [comment]
Sure:

```json
{
    "@context": [
        "https://w3id.org/ro/crate/1.1/context",
        { "@vocab": "http://schema.org/" },
        { "txc": { "@id": "http://purl.archive.org/textcommons/terms#" } },
        { "@base": null },
        {
            "textualValue": "https://some.org/schema/text",
            "numericValue": "https://some.org/schema/number"
        }
    ],
    "@graph": [
        {
            "@id": "ro-crate-metadata.json",
            "@type": "CreativeWork",
            "conformsTo": { "@id": "https://w3id.org/ro/crate/1.1" },
            "about": { "@id": "./" }
        },
        {
            "@id": "./",
            "@type": ["Dataset"],
            "textualValue": "Some text",
            "numericValue": 123
        }
    ]
}
```

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/17a2cbe7-f940-46ac-af0f-adba7a48d7d0">
