### ISSUE TITLE
Component: Add a boolean type component

### ISSUE THREAD

**Issue by marcolarosa** [describo/crate-builder-component#20]

**Comment by marcolarosa** [comment]
@beepsoft 

Is this something you guys could tackle? Add it as another primitive.

**Comment by csontosreka** [comment]
I'll get to this issue soon. Do you prefer using [switch](https://element-plus.org/en-US/component/switch.html) or [checkbox](https://element-plus.org/en-US/component/checkbox.html) components?

**Comment by marcolarosa** [comment]
Good question. I think I prefer a checkbox as it will be more familiar to people. What do you think?

**Comment by marcolarosa** [comment]
Completed by @csontosreka https://github.com/describo/crate-builder-component/pull/97
