### ISSUE TITLE
Storybook problems

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#50]
Trying version 0.35.1 and some of the storybook stories fail. For example:

<img width="1490" alt="image" src="https://github.com/describo/crate-builder-component/assets/1926265/46bb3a2a-dbaf-4472-9747-83538ddf176f">

I would like to add a story for `Shell.component.wc.vue` to be able to check whether the WebComponent specific functionalities work in vue. For example, setting the new `enableReverseLinkBrowser` value doesn't seem to work for me right now and I try to figure out whether the problem is in the vue/wc/react layer. A `Shell.component.wc.stories.js` could help in this.

**Comment by marcolarosa** [comment]
Fixed in the latest release. The internal data form had changed so the story data needed updating.

I also tested that all configuration options to disable UI controls were working and they are.
