### ISSUE TITLE
When editing field in a group the editor always jumps to the About group

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#52]
Previously, when we edited a field value in a group the editor stayed at the currently selected group where the field was present, but now it always jumps back to the About group. This way the users always loose the editing context and need to go back to the group and find the field they want to edit.

[describo-group-bug.webm](https://github.com/describo/crate-builder-component/assets/1926265/ee08f72f-cb27-4302-8027-3a34a86d2ab7)

**Comment by beepsoft** [comment]
It seems to be a newly added (789a1d5d00a21e1d2ce5ac0487d6b9ae91840c9c) behaviour here:

https://github.com/describo/crate-builder-component/blob/6a11d706ac6d76c1cc91c08735b3cef9175c45f3/src/crate-builder/RenderEntity/Shell.component.vue#L297

**Comment by marcolarosa** [comment]
Ahh yeah - sorry about that! I set it in the wrong place. It needs to be set when the profile changes. If the new profile does not have a tab named as the one it's on then the view goes blank. Fix coming soon.

**Comment by marcolarosa** [comment]
should be fixed by f6545b59965f91c6055742a9145cad3d285be175

**Comment by beepsoft** [comment]
Thanks for the quick fix, @marcolarosa! I published the updated react component as well.
