### ISSUE TITLE
configuration.webComponent is undefined in AutoComplete.component.vue

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#54]
Setting the `webComponent` configuration option doesn't seem to have effect anymore as the value of `configuration.webComponent` is always undefined here:

https://github.com/describo/crate-builder-component/blob/5b93d4d86acd957e3345ae21fc04d3fd2907bbe9/src/crate-builder/RenderEntity/AutoComplete.component.vue#L83-L85

I checked both in the Vue test app and in the web component build and in both cases the value of `configuration.webComponent` (and actually any `configuration.*` value, eg. `configuration.language`,  is undefined).

As a result the autocomplete field is now always cleared because the web component related workaround in the above code is not run.

**Comment by marcolarosa** [comment]
Check 0.37.2 and see if it works now please. As configuration is now computed we need to get to the properties via configuration.value. 2c26f0ee814a38601601a5efc34649227310c574

**Comment by beepsoft** [comment]
It works now! Thanks for the quick fix!
