### ISSUE TITLE
Controls disappears when clearing value of a non multiple item

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#55]
In our Profile we have an input definition like this:

```json
        {
          "id": "https://dataverse.org/schema/citation/authorAffiliation",
          "name": "authorAffiliation",
          "label": "Affiliation",
          "help": "The name of the entity affiliated with the author, e.g. an organization's name",
          "type": [
            "Text"
          ],
          "required": false,
          "multiple": false
        },
```

If we delete the value using the delete icon then the field's value is deleted and we have a "+ Text" button again.

However, if instead of the delete button, we just clear all the text in the field, we cannot edit it anymore, add a new value, or delete it because no controls appear.

All this only happens with `"multiple": false` fields.

[screencast-github.com-2023.06.13-14_33_14.webm](https://github.com/describo/crate-builder-component/assets/1926265/5de26cb6-6eaf-446a-956c-dc3221367a96)

**Comment by marcolarosa** [comment]
Checkout 0.37.3. Good find!
