### ISSUE TITLE
After providing an incorrect URL, and change it to a correct URL, the approval icon remains inactive.

### ISSUE THREAD

**Issue by csontosreka** [describo/crate-builder-component#56]
I filled out a field of type URL without specifying the protocol during the completion. Then a message appeared below the field stating that it would be mandatory to provide it. The field remained editable, but the green checkmark icon at the end of the line became inactive, and even after correcting the URL. After a click it saves the new URL, but it is visually deceptive. 

<img width="671" alt="image" src="https://github.com/describo/crate-builder-component/assets/61116319/857d7ac3-d6bc-46c9-9151-0fd087b9e7a9">
<img width="665" alt="image" src="https://github.com/describo/crate-builder-component/assets/61116319/f558f478-99d0-4c3c-9d02-6ca37c402151">

**Comment by marcolarosa** [comment]
Thanks for the report. A fix will come out in the next release (probably) next week
