### ISSUE TITLE
In the date field, it is not possible to manually enter dates before 1000, only select them

### ISSUE THREAD

**Issue by csontosreka** [describo/crate-builder-component#57]
It is currently difficult to navigate to negative dates. If it were possible to also enter the selected date in the text part, it would be less inconvenient. However, at the moment, one can only navigate one by one or by tens. For example, if someone wants to input a date before our current era, it would require a significant number of clicks.

**Comment by marcolarosa** [comment]
Ahh this is a quirk of the date component in element plus. You need to add the year as 4 digits so try adding 0900-06-06 rather than 900... and it will work
