### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by marcolarosa** [describo/crate-builder-component#59]
hi @beepsoft. Can you please translate "Associate any entity (lookup by identifier or name)". I needed to add another property called "associate_any_prompt" for a new profile feature.

**Comment by beepsoft** [comment]
Sure, but I couldn't find it anywhere in the code (I thought it would be in en.js as a reference):

https://github.com/search?q=repo%3Adescribo%2Fcrate-builder-component%20associate_any_prompt&type=code

Anyways, should I add it to hu.js in a PR?

**Comment by marcolarosa** [comment]
Ahh yeah - it's in my working branch for now. If you can just write the translation into this ticket I'll copy it into the localisation file.

**Comment by beepsoft** [comment]
Ok, so it is "Bármely entitás hozzárendelése (azonosító vagy név alapján)"
