### ISSUE TITLE
Layout tab selection reset when changing crate

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#67]
There seems to be a behavioural change between 0.37.2 and the current 0.38.2 version.

In 0.37.2 when switching between crates, the layout selection is remembered. In my case I selected the "Languages" tab. As I switch between "Complex Item" and "Large Crate" this selection remains:

[screencast-localhost_9000-2023.08.28-21_50_11-0.37.2.webm](https://github.com/describo/crate-builder-component/assets/1926265/df28b948-6aa0-47e1-b0ae-f54e71efc15f)

In 0.38.2, however, using the same profile and switching between  "Complex Item" and "Large Crate" the "Lanuages" tab selection is forgot and after the switch we always arrive at the About tab:

[screencast-localhost_9000-2023.08.28-21_52_23-0.38.3.webm](https://github.com/describo/crate-builder-component/assets/1926265/4fbf9f9f-8ba5-46d1-81bd-8f32d7cbe3c8)

In our app we expect the behaviour of 0.37.2, but the current behaviour could also make sense for others, so it maybe a configurable option.

**Comment by marcolarosa** [comment]
Handled in ace47174349f9b7c44d40a4c48cbc663691f5c9d
