### ISSUE TITLE
Switching to MIT license

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#69]
I recommend switching from the current GPL to a more permissive license such as MIT. The license for the Crate Builder React component is already MIT, and within the React/Vue community, the MIT license is generally preferred. Both Vue and React themselves are licensed under MIT.

I believe that making this change could facilitate and encourage the future adoption of Describo in other RO-Crate projects that are written in either Vue or React.

**Comment by marcolarosa** [comment]
Ok. This sounds reasonable to me.

The choice of GPLv3 was made by others who provided the funding for the earlier versions of describo. As it is now unfunded I think we can make this change. I just want to hold off for a little while to see if anyone else has an opinion on the matter so I'll leave this ticket as is for now.

**Comment by beepsoft** [comment]
As there seem to be no other opinion, what do you think about switching the license?

**Comment by marcolarosa** [comment]
Can you do this please and provide a pull request?

**Comment by beepsoft** [comment]
Sure, #87

**Comment by marcolarosa** [comment]
Done thanks @beepsoft
