### ISSUE TITLE
Check toggle to highlight required properties.

### ISSUE THREAD

**Issue by marcolarosa** [describo/crate-builder-component#77]
@beepsoft 

Please have a look at https://github.com/describo/crate-builder-component/tree/higlight-required-properties and let me know what you think.

There is now an extra button that allows the user to make the required properties without data more visible. It only appears when there are required fields without data.

I know it's not how you envisaged but it does make the required properties without data much more visible without tightly coupling the component internals to the outer app which i'm not a big fan of.

**Comment by beepsoft** [comment]
I tried it, that's quite helpful for users, I agree, thanks!

**Comment by marcolarosa** [comment]
done with aaf5ad4552fd9dc5ef3317020ddb17f78c03bd86
