### ISSUE TITLE
Red triangle is displayed when no required field is present

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#79]
If I navigate to a context entity which doesn't have any required fields at all the red triangle button still appears and pressing it has no effect, because there's no empty required property. This seems confusing. Would it be possible not to display the button in cases when it has no function?

<img width="1091" alt="image" src="https://github.com/describo/crate-builder-component/assets/1926265/be2346d7-118f-4a58-9bb8-e54edc18e442">

**Comment by marcolarosa** [comment]
Ahh yeah - that was a bug. I fixed it today. Update your code and it should be gone.

**Comment by marcolarosa** [comment]
Just to add: I was working out whether there were required fields in tabbed layout but not in untabbed.

**Comment by beepsoft** [comment]
Great, thanks @marcolarosa, I close it then.
