### ISSUE TITLE
Additional input constraints in profiles

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#81]
Profiles currently define 3 constraints for inputs
- type (Text, Number, Url, etc.)
- required or not
- multiplicable or not

It would be great to have further type specific constraints for inputs - similar to JSON Schema property constraints - and enforce them via the current validation mechanism.

The possible constraint, which could be added per type:

**Text**
- `minLength`: minimum required length for value
- `maxLength`: maximum allowed length for value
- `regex`: a regular expression the value has to match

**TextArea**
- `minLength`: minimum required length for value
- `maxLength`: maximum allowed length for value
- `regex`: a regular expression the value has to match

**Number**
- `minValue`: minimum possible value to be entered
- `maxValue`: maximum possible value to be entered
- `numberType`: one or many of "any", "long", "int", "float", "double". It maybe an array to allow specifying any of the possble numberType values

**Date**
- `granularity`: may have the values "year" (YYYY), "month" (YYYY-MM), "day" (YYYY-MM-DD). It maybe an array to allow specifying any of the possible granularity values

**DateTime**
- `dateGranularity`: may have the values "year" (YYYY), "month" (YYYY-MM), "day" (YYYY-MM-DD). It maybe an array to allow specifying any of the possible granularity values
- `timeGranularity`: may have the values "hour" (hh), "minute" (hh:mm), "second" (hh:mm:ss).It maybe an array to allow specifying any of the possible granularity values

I think the Text, TextArea and Number constraints could be easily added. The Date/DateTime might be trickier, but also valid use cases, for example, Dataverse has this kind of Date field, which allows entering either YYYY, or YYYY-MM or YYYY-MM-DD format dates.

**Comment by marcolarosa** [comment]
These are great ideas.

re: the Date / DateTime rules: The date picker supports the format field which satisfies this idea but I think it could get confusing when the user tries to enter a year in the format YYYY and ends up with that year as an ISO String. These  cases can be modeled as a Text field with min = 4, max = 4 and an appropriate regex (Ie check 4 digits) And it means dates always output iSO Strings as expected (and this is what I do in my own app - a date field in ISO format and a date as a simple string).

Leave it with me - this is a good first task for someone I know that wants to start helping out.  If they can't do it, then we can talk about your team providing a pull request or me doing it when i can.

**Comment by beepsoft** [comment]
@marcolarosa, do you think you or your helper will be able to proceed with this issues? Or should our team  provide a PR for this?

**Comment by marcolarosa** [comment]
Umm yeah - if you guys can do this that would be great. Thankyou.

**Comment by beepsoft** [comment]
OK, we'll start working on it!

**Comment by marcolarosa** [comment]
@beepsoft Any news on this?

**Comment by beepsoft** [comment]
Yes, we have this working internally, I just need to make it ready for PR.

**Comment by marcolarosa** [comment]
Done!! Well done guys - this is great!
