### ISSUE TITLE
Clearing a text field makes the field disappear

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#83]
In 0.50.3 (but it also happens in older version, eg. 0.46.1) when I delete a text field's content with backspace and press Enter or green button, the text field disappears and and empty string value is generated in the json. 

Here I add some text fields, delete them using backspace+enter and the ro crate json ends up having 3 empty strings. As no field is displayed for the empty values these cannot actually be deleted. When a field's value becomes empty it should produce no value in the json at all, I think. It probably should behave as a delete operation using the red button.

[screencast-localhost_9000-2023.10.27-09_11_13.webm](https://github.com/describo/crate-builder-component/assets/1926265/38a7bec5-8126-44f4-a27e-b3b6e79aa908)

**Comment by beepsoft** [comment]
This is even more noticeable and problematic when only a single value can be entered (Title in this case). This is the UI in this case with a cleared, empty value:

<img width="639" alt="image" src="https://github.com/describo/crate-builder-component/assets/1926265/808b9951-4dab-4ec6-9a14-eb7c8fc4c974">

**Comment by marcolarosa** [comment]
Please check out 0.50.4. This should be resolved now. 

Sorry about the delay - i was knocked out with covid!

**Comment by beepsoft** [comment]
Thanks @marcolarosa, I will check it later this week!
