### ISSUE TITLE
When adding new entity, the select field loads infinitely

### ISSUE THREAD

**Issue by csontosreka** [describo/crate-builder-component#91]
To replicate the issue, follow these steps:
- Select an empty crate with either the "A profile with all primitives and no groups" or "A profile with all primitives and groups" profile.
- Attempt to add a new Person or Organization on ANY entity.
- Input text into the designated field.
- The autocomplete feature will enter an endless loading state because of a CORS error.

![image](https://github.com/describo/crate-builder-component/assets/61116319/186ef8df-a7e3-4707-b2fd-470189c704d0)

Adding this to environment in the docker-compose.yml solved the issue:
```
 environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms750m -Xmx750m
            - xpack.security.enabled=false
            - node.name=search
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=http://localhost:9000" # Adjust the URL to match your frontend's origin
            - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
            - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
```

**Comment by marcolarosa** [comment]
Thanks @csontosreka ! I use a browser plugin to turn CORS on and off (https://mybrowseraddon.com/access-control-allow-origin.html) but this is much, much better! It never crossed my mind.
