### ISSUE TITLE
What is your name?

### ISSUE THREAD

**Issue by marcolarosa** [describo/crate-builder-component#98]
@csontosreka Hey - you've done quite a bit for describo and I would like to acknowledge that!

I've put you onto the team page @ https://describo.github.io/documentation/team.html but I don't actually know your name! I'm so sorry.

Please let me know and I'll fix your reference. Also, if you'd like me to put up your linked in account send that through as well.

**Comment by csontosreka** [comment]
Hi! Thank you very much! My name is Réka Csontos.

**Comment by marcolarosa** [comment]
Done - thankyou! Send through your linked in page so I can add that (if you want) and we can connect there.
